Name main function for React support.
bradhowes/remarkable-katex pull request #5
Opened 2020-10-24 20:55 UTC by madstk1

There doesn't seem to be any support for React, since the function isn't named in the export. Also, since the name includes a dash (-), it doesn't import correctly, anyway.

With this, you should be able to import the plugin like this:

```js
   import rkatex from 'remarkable-katex';
```

2020-10-26 08:57 UTC, madstk1 commented
Since the default export isn't immediately obvious, there should be an example in the README or wiki.

2020-10-26 16:21 UTC, bradhowes requested changes
This looks fine, but could you please change to use the same function style?
`const rkatex = (md, options) => {`

2020-10-26 16:22 UTC, bradhowes commented
Hi Max. Thanks for taking the time to contribute these changes.

2020-10-27 14:14 UTC, merged

2020-10-27 14:14 UTC, bradhowes commented
Thanks again for your effort!